Quiz-Application.Web/Controllers/ScoreController.cs
using System.IO;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DinkToPdf.Contracts;
using DinkToPdf;
using Quiz_Application.Web.Extensions;
using Quiz_Application.Web.Authentication;
using Quiz_Application.Services.Entities;
using Quiz_Application.Services.Repository.Interfaces;
using System.Drawing.Imaging;
using Microsoft.AspNetCore.Authorization;

namespace Quiz_Application.Web.Controllers
{
    [Authorize(Roles = "candidate")]
    public class ScoreController : Controller
    {
       private readonly IConverter _converter;
       private readonly ILogger<ScoreController> _logger;
       private readonly IResult<Services.Entities.Result> _result;
       private readonly ICandidate<Services.Entities.Candidate> _candidate;

        public ScoreController(ILogger<ScoreController> logger, IResult<Services.Entities.Result> result, IConverter converter, ICandidate<Candidate> candidate)
        {
            _logger = logger;
            _result = result;
            _converter = converter;
            _candidate = candidate;
        }
        public async Task<IActionResult> Result()
       {
            try
            {
                //Candidate _objCandidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");

                var identity = HttpContext.User.Identity.Name;
                IQueryable<Candidate> iqCandidate = await _candidate.SearchCandidate(e => e.UserName.Equals(identity));
                Candidate _objCandidate = iqCandidate.FirstOrDefault();


                IEnumerable<QuizAttempt> _obj = await _result.GetAttemptHistory(_objCandidate.Candidate_ID);
                Root objRoot = new Root(){
                    objCandidate= _objCandidate,
                    objAttempt = _obj.ToList() 
                };               
                return View(objRoot);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally 
            {
            }
        }

        [HttpPost]
        [Route("~/api/Report")]
        public async Task<IActionResult> Report(ReqReport argRpt)
        {
            try
            {
                IEnumerable<QuizReport> lst = await _result.ScoreReport(argRpt);
                return Ok(lst.ToList());
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally
            {
            }
        }

        [HttpPost]
        [Route("~/api/CreatePDF")]
        public async Task<IActionResult> CreatePDF(ReqCertificate argPDFRpt)
        {
            ResPDF obj = null;
            try
            {                
                string html = await _result.GetCertificateString(argPDFRpt);
                string UploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles/Report");
                string UniqueFileName = argPDFRpt.CandidateID + "_Certificate.pdf";
                string UploadPath = Path.Combine(UploadFolder, UniqueFileName);
                var globalSettings = new GlobalSettings
                {
                    ColorMode = DinkToPdf.ColorMode.Color,
                    Orientation = Orientation.Landscape,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings { Top = 10, Bottom = 10 },
                    Out = UploadPath
                };
                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = html,
                    WebSettings = { DefaultEncoding = "utf-8" },
                };
                var htmlToPdfDocument = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings },
                };
                _converter.Convert(htmlToPdfDocument);
                obj = new ResPDF();
                obj.IsSuccess = true;
                obj.Path = "/UploadedFiles/Report/" + UniqueFileName;
            }
            catch (Exception ex)
            {
                obj.IsSuccess = false;
                obj.Path = null;
                throw new Exception(ex.Message, ex.InnerException);                 
            }
            finally
            {
            }
            return Json(obj);
        }
                
    }
}

Quiz-Application.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quiz_Application</title>
    <link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Open Sans", sans-serif
        }
    </style>
</head>
<body class="w3-theme-l5">

    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
            <a class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>EasyQuiz</a>
            <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-book"></i> Quiz</a>
            <a asp-controller="Score" asp-action="Result" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-server"></i> Score Report</a>
            <div class="w3-dropdown-hover w3-hide-small">
                <button class="w3-button w3-padding-large" title="Notifications"><i class="fa fa-cog"></i> Settings</button>
                <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
                    <a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Edit Profile</a>
                </div>
            </div>
            <a asp-controller="Auth" asp-action="Login" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-server"></i> Admin Login</a>

            <a asp-action="Logout" asp-controller="Account" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="Sign out">
                <img src="https://www.w3schools.com/w3images/avatar2.png" class="w3-circle" style="height:23px;width:23px" alt="Avatar">
            </a>
        </div>
    </div>

    <!-- Navbar on small screens -->
    <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
        <a asp-controller="EasyQuiz" asp-action="Privacy" class="w3-bar-item w3-button w3-padding-large">EasyQuiz</a>
        <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-padding-large">Home</a>
        <a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
        <a asp-controller="Score" asp-action="Result" class="w3-bar-item w3-button w3-padding-large">Score Report</a>
        <a asp-action="Logout" asp-controller="Account" class="w3-bar-item w3-button w3-padding-large">Sign out</a>
    </div>

    @RenderBody()

    <!-- Footer -->
    <footer class="w3-container w3-theme-d3 w3-padding-16">
        <marquee direction="left"><h6>Things to remember ! The test is not official, it's just a nice way to see how much you know, or don't know, about the skill.</h6></marquee>
    </footer>
    <footer class="w3-container w3-theme-d5 w3-padding-16">
        <h6>Developed by <a href="https://www.c-sharpcorner.com/members/arnab-mukherjee" target="_blank">Arnab Mukherjee</a></h6>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <environment include="Development">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    
    <script type="text/javascript">
        // Accordion
        function myFunction(id) {
            var x = document.getElementById(id);
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
                x.previousElementSibling.className += " w3-theme-d1";
            } else {
                x.className = x.className.replace("w3-show", "");
                x.previousElementSibling.className =
                    x.previousElementSibling.className.replace(" w3-theme-d1", "");
            }
        }

        // Used to toggle the menu on smaller screens when clicking on the menu button
        function openNav() {
            var x = document.getElementById("navDemo");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>